// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRSbfy_s60meClUhySGr3zprsIW7umB2I',
    appId: '1:990417170613:web:32cd8b742aa7f0617a0efc',
    messagingSenderId: '990417170613',
    projectId: 'yosandekaiekbo',
    authDomain: 'yosandekaiekbo.firebaseapp.com',
    storageBucket: 'yosandekaiekbo.firebasestorage.app',
    measurementId: 'G-YCM52EJYG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD41E0y7wGnCeKphd6A4xiIHIggLan2Ans',
    appId: '1:990417170613:android:3a80fab55643e8a57a0efc',
    messagingSenderId: '990417170613',
    projectId: 'yosandekaiekbo',
    storageBucket: 'yosandekaiekbo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSHOX0OuXYb5fdR50sHWZ5HEo84Skafpo',
    appId: '1:990417170613:ios:302b2f22aebaccca7a0efc',
    messagingSenderId: '990417170613',
    projectId: 'yosandekaiekbo',
    storageBucket: 'yosandekaiekbo.firebasestorage.app',
    iosBundleId: 'com.example.yosanDeKakeibo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSHOX0OuXYb5fdR50sHWZ5HEo84Skafpo',
    appId: '1:990417170613:ios:302b2f22aebaccca7a0efc',
    messagingSenderId: '990417170613',
    projectId: 'yosandekaiekbo',
    storageBucket: 'yosandekaiekbo.firebasestorage.app',
    iosBundleId: 'com.example.yosanDeKakeibo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRSbfy_s60meClUhySGr3zprsIW7umB2I',
    appId: '1:990417170613:web:bed61ed26cd8a5037a0efc',
    messagingSenderId: '990417170613',
    projectId: 'yosandekaiekbo',
    authDomain: 'yosandekaiekbo.firebaseapp.com',
    storageBucket: 'yosandekaiekbo.firebasestorage.app',
    measurementId: 'G-DB25VT7BRV',
  );
}
