// Mocks generated by Mockito 5.4.5 from annotations
// in yosan_de_kakeibo/test/mocks/mock_medal_repository.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:yosan_de_kakeibo/models/medal.dart' as _i4;
import 'package:yosan_de_kakeibo/repositories/medal_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MedalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMedalRepository extends _i1.Mock implements _i2.MedalRepository {
  MockMedalRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Medal>> getMedals() =>
      (super.noSuchMethod(
            Invocation.method(#getMedals, []),
            returnValue: _i3.Future<List<_i4.Medal>>.value(<_i4.Medal>[]),
          )
          as _i3.Future<List<_i4.Medal>>);

  @override
  _i3.Future<void> saveMedals(List<_i4.Medal>? medals) =>
      (super.noSuchMethod(
            Invocation.method(#saveMedals, [medals]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
